<?php
namespace app\controllers;
use app\Controllers;
use app\models\AddressModel;
use app\models\District;
use app\models\Region;
use app\models\ResponseJSON;
use http\Exception;
use Yii;
use yii\web\Controller;
use yii\web\Response;

class ApiController extends Controller
{
    public function beforeAction($action)
    {

        Yii::$app->request->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionAddressGet()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = AddressModel::find()->all();
        $response = new ResponseJSON();
        $response->status = 'ok';
        $response->data = $model;
        $response->message = '';
        return $response;
    }

    /**
     * @param null $id
     * @return ResponseJSON
     */
    public function actionRegion($id = null)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $response = new ResponseJSON();

        if ($id == null) {
            try {
                $model = Region::find()->all();
                $response->status = 'ok';
                $response->data = $model;
                $response->message = '';
                return $response;
            } catch (Exception $e) {
                $response->status = 'error';
                $response->message = $e->getMessage();
                return $response;
            }
        } else {
            try {
                $model = Region::findOne(['id' => $id]);
                $res = $model->toArray();
                $dis = ['districts' => $model->districts];
                $res = array_merge($res, $dis);
                $response->status = 'ok';
                $response->data = $res;
                $response->message = '';
                return $response;
            } catch (Exception $e) {
                $response->status = 'error';
                $response->message = $e->getMessage();
                return $response;
            }
        }
    }

    /**
     * @param null $id
     * @return ResponseJSON
     */
    public function actionDistrict($id = null)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $response = new ResponseJSON();
        if($id == null)
        {
            try {
                $model = District::find()->all();
                $response->status = 'ok';
                $response->data = $model;
                $response->message = '';
                return $response;
            } catch (Exception $e) {
                $response->status = 'error';
                $response->message = $e->getMessage();
                return $response;
            }
        }
        else
        {
            try {
                $model = District::findOne(['id' => $id]);
                $res = $model->toArray();
                $dis = ['region' => $model->region];
                $res = array_merge($res , $dis);
                $response->status = 'ok';
                $response->data = $res;
                $response->message = '';
                return $response;
            } catch (Exception $e) {
                $response->status = 'error';
                $response->message = $e->getMessage();
                return $response;
            }
        }

    }


}