<?php
namespace app\controllers;
use app\Controllers;
use app\models\AddressModel;
use app\models\District;
use app\models\Region;
use app\models\ResponseJSON;
use http\Exception;
use Yii;
use yii\db\Query;
use yii\web\Controller;
use yii\web\Response;

class ApiController extends Controller
{
    public function beforeAction($action)
    {

        Yii::$app->request->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionAddress()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
//        $model = Yii::$app->db->createCommand("SELECT region.name AS Region,district.name AS District,address.address AS Address FROM address LEFT JOIN district district ON district.id = address.`district_id` LEFT JOIN region region ON region.id = district.`region_id`")->queryAll();
        $query = new Query;
        $query->select("region.name AS Region,district.name AS District,address.address AS Address")
            ->from('address')
            ->Leftjoin("district",' district.id = address.`district_id`')
            ->Leftjoin("region",' region.id = district.`region_id`');
// build and execute the query
        $model = $query->all();

//        $model = AddressModel::find()->all();
        $response = new ResponseJSON();
        $response->status = 'ok';
        $response->message = '';
        $response->data = $model;

        return $response;
    }

    /**
     * @param null $id
     * @return ResponseJSON
     */
    public function actionRegion($id = null)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $response = new ResponseJSON();

        if ($id == null) {
            try {
                $model = Region::find()->all();
                $response->status = 'ok';
                $response->data = $model;
                $response->message = '';
                return $response;
            } catch (Exception $e) {
                $response->status = 'error';
                $response->message = $e->getMessage();
                return $response;
            }
        } else {
            try {
                $model = Region::findOne(['id' => $id]);
                $res = $model->toArray();
                $dis = ['districts' => $model->districts];
                $res = array_merge($res, $dis);
                $response->status = 'ok';
                $response->data = $res;
                $response->message = '';
                return $response;
            } catch (Exception $e) {
                $response->status = 'error';
                $response->message = $e->getMessage();
                return $response;
            }
        }
    }

    /**
     * @param null $id
     * @return ResponseJSON
     */
    public function actionDistrict($id = null)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $response = new ResponseJSON();
        if($id == null)
        {
            try {
                $model = District::find()->all();
                $response->status = 'ok';
                $response->data = $model;
                $response->message = '';
                return $response;
            } catch (Exception $e) {
                $response->status = 'error';
                $response->message = $e->getMessage();
                return $response;
            }
        }
        else
        {
            try {
                $model = District::findOne(['id' => $id]);
                $res = $model->toArray();
                $dis = ['region' => $model->region];
                $res = array_merge($res , $dis);
                $response->status = 'ok';
                $response->data = $res;
                $response->message = '';
                return $response;
            } catch (Exception $e) {
                $response->status = 'error';
                $response->message = $e->getMessage();
                return $response;
            }
        }

    }

    


}